all: clean clear compile compile2

clean:
	@rm -f *.out
	@rm -f *.out
	@rm -f HungryVeryMuch
	@rm -f PideShop


clear:
	@clear

compile:
	@gcc -o PideShop server.c

compile2:
	@gcc -o HungryVeryMuch client.c
